version: '3.8'

services:
  analyzer:
    build: .
    container_name: analyzer-standalone
    ports:
      - "8080:8080"
    environment:
      - ANALYZER_PORT=8080
      - ANALYZER_ID=standalone-analyzer
      - SPRING_PROFILES_ACTIVE=docker
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/api/v1/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped
    # Optional: Add logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"